services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      - API_KEY=${API_KEY}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${APP_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  docs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - ${MKDOCS_PORT}:8000


volumes:
  postgres_data:
