FROM python:3.12-slim

WORKDIR /mkdocs

RUN pip install poetry

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

COPY . .

RUN mkdocs build --clean
CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]
