"""Add weather_daily_summaries table

Revision ID: c594799a5834
Revises:
Create Date: 2024-09-28 14:44:23.053775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c594799a5834'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('temp_afternoon', sa.Float(), nullable=False),
    sa.Column('temp_night', sa.Float(), nullable=False),
    sa.Column('temp_evening', sa.Float(), nullable=False),
    sa.Column('temp_morning', sa.Float(), nullable=False),
    sa.Column('temp_range', sa.Float(), nullable=False),
    sa.Column('cloud_cover_afternoon', sa.Float(), nullable=False),
    sa.Column('humidity_afternoon', sa.Float(), nullable=False),
    sa.Column('precipitation_total', sa.Float(), nullable=False),
    sa.Column('pressure_afternoon', sa.Float(), nullable=False),
    sa.Column('wind_speed_max', sa.Float(), nullable=False),
    sa.Column('wind_direction_max', sa.Float(), nullable=False),
    sa.Column('temp_variability_index', sa.Float(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('extreme_temperature', sa.Boolean(), nullable=False),
    sa.Column('extreme_precipitation', sa.Boolean(), nullable=False),
    sa.Column('extreme_wind', sa.Boolean(), nullable=False),
    sa.Column('humidex', sa.Float(), nullable=False),
    sa.Column('precipitation_intensity', sa.String(), nullable=False),
    sa.Column('rolling_mean_temp', sa.Float(), nullable=True),
    sa.Column('wind_chill', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_daily_summaries_date'), 'weather_daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_weather_daily_summaries_id'), 'weather_daily_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_weather_daily_summaries_latitude'), 'weather_daily_summaries', ['latitude'], unique=False)
    op.create_index(op.f('ix_weather_daily_summaries_longitude'), 'weather_daily_summaries', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_daily_summaries_longitude'), table_name='weather_daily_summaries')
    op.drop_index(op.f('ix_weather_daily_summaries_latitude'), table_name='weather_daily_summaries')
    op.drop_index(op.f('ix_weather_daily_summaries_id'), table_name='weather_daily_summaries')
    op.drop_index(op.f('ix_weather_daily_summaries_date'), table_name='weather_daily_summaries')
    op.drop_table('weather_daily_summaries')
    # ### end Alembic commands ###
